services:
  visioner_unit_gate:
    container_name: visioner_unit_gate_server
    build:
      context: .
      network: host
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8080:8080"
    restart: "always"
    privileged: true
    volumes:
      - "/dev:/dev"